// AUTOKEYS REMAPS PRO - CONFIGURACIÓN SUPABASE

export const SUPABASE_URL = "https://zvsekmvzkmymwostezwf.supabase.co";

export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2c2VrbXZ6a215d3dvc3RlendmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNjA2MDAsImV4cCI6MjA5NTgzNjYwMH0.6PGVHDSPz0o7g8XP2OXSM8RpAupKGxbhaSLw3quUORQ";
